import { useState } from "react";
import type { Context, Exchange, ImportBatch, People, Person, Program, Role, Settings, Training } from "./api";
import { download, ops, opsFile } from "./api";
import { Banner, Empty, Field, Panel, State, Table, date, go, human, useAction, useLoad } from "./shared";

export function PeoplePage({ owner }: { owner: boolean }) {
  const load = useLoad<People>("/people"); const programs = useLoad<Program[]>("/programs"); const action = useAction(load.refresh); const [link, setLink] = useState(""); const [delivery, setDelivery] = useState("");
  return <><State {...load} /><Banner {...action} /><Panel title="Invite staff"><p>Staff accept an invitation and choose a password. Existing users enter their current password to join another university.</p><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(async () => { const created = await ops<{ path: string; email_delivery: string }>("/invitations", "POST", { email: form.get("email"), role: form.get("role"), deliver_email: form.has("deliver_email") }); setLink(window.location.href.split("#")[0] + created.path); setDelivery(created.email_delivery); }, "Invitation created."); }}>
    <Field label="Staff email"><input name="email" type="email" required /></Field><Field label="Workspace access"><select name="role">{(["reviewer", "admissions_manager", "finance_viewer", "auditor", ...(owner ? ["university_owner"] : [])]).map(role => <option key={role} value={role}>{human(role)}</option>)}</select></Field><button className="primary-button" disabled={action.busy}>Create invitation</button>
    <label className="workflow-check"><input type="checkbox" name="deliver_email" />Email this invitation using the configured mail service.</label>
  </form>{delivery ? <p role="status">{delivery === "sent" ? "Invitation email sent." : delivery === "not_configured" ? "Email delivery is not configured. Copy and share the invitation link." : delivery === "failed" ? "Email delivery failed. Your invitation is valid; copy and share its link." : "Copy and share the invitation link."}</p> : null}{link ? <div className="workflow-toolbar"><Field label="Invitation link"><input readOnly value={link} /></Field><button className="secondary-button" onClick={() => void action.run(() => navigator.clipboard.writeText(link), "Invitation link copied.")}>Copy invitation</button></div> : null}</Panel>
    <Panel title="People with access">{load.data?.people.map(person => <PersonCard key={`${person.id}:${person.revision}`} person={person} programs={programs.data ?? []} data={load.data!} refresh={load.refresh} />)}</Panel>
    <Panel title="Pending invitations"><Table headings={["Email", "Access", "Expires", "Status", "Action"]}>{load.data?.invitations.map(invite => <tr key={invite.id}><td>{invite.email}</td><td>{human(invite.role)}</td><td>{date(invite.expires_at)}</td><td>{invite.accepted ? "Accepted" : invite.revoked ? "Revoked" : "Pending"}</td><td>{!invite.accepted && !invite.revoked ? <button className="ghost-button" disabled={action.busy} onClick={() => void action.run(() => ops(`/invitations/${invite.id}/revoke`, "POST"))}>Revoke invitation</button> : null}</td></tr>)}</Table></Panel>
    <Panel title="Department queues"><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops("/departments", "POST", { name: form.get("name") })); }}><Field label="Department name"><input name="name" required maxLength={200} /></Field><button className="secondary-button" disabled={action.busy}>Add department</button></form><p>{load.data?.departments.map(d => d.name).join(", ") || "No department queues."}</p></Panel>
  </>;
}

function PersonCard({ person, programs, data, refresh }: { person: Person; programs: Program[]; data: People; refresh: () => void }) {
  const action = useAction(refresh);
  return <article className="workflow-card"><h3>{person.email}</h3><p>{human(person.role)} · {person.status} · Last sign-in {date(person.last_login_at)}</p><Banner {...action} />
    {person.role === "reviewer" ? <details><summary>{person.open_reviews} / {person.workload_limit} open reviews · Edit coverage</summary><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(`/people/${person.user_id}/coverage`, "PUT", { workload_limit: Number(form.get("workload")), program_ids: form.getAll("programs"), department_ids: form.getAll("departments") })); }}><Field label="Workload limit"><input name="workload" type="number" min={1} max={250} defaultValue={person.workload_limit} /></Field><Field label="Program coverage (empty means all)"><select multiple name="programs" defaultValue={person.program_ids}>{programs.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Department coverage (empty means all)"><select multiple name="departments" defaultValue={person.department_ids}>{data.departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><button className="secondary-button" disabled={action.busy}>Save coverage</button></form></details> : null}
  </article>;
}

export function SettingsPage({ context, refresh }: { context: Context; refresh: () => void }) {
  const [form, setForm] = useState<Settings>(context.settings); const action = useAction(refresh); const programs = useLoad<Program[]>("/programs");
  return <><Banner {...action} /><Panel title="Institution setup"><form onSubmit={event => { event.preventDefault(); void action.run(() => ops("/settings", "PUT", form)); }}><div className="workflow-grid"><Field label="Workspace display name"><input required maxLength={200} value={form.brand_name} onChange={event => setForm({ ...form, brand_name: event.target.value })} /></Field><Field label="Brand accent"><input type="color" value={form.brand_color} onChange={event => setForm({ ...form, brand_color: event.target.value })} /></Field><Field label="Default secure-link expiry days"><input type="number" min={1} max={90} value={form.secure_link_expiry_days} onChange={event => setForm({ ...form, secure_link_expiry_days: Number(event.target.value) })} /></Field></div>
    <label className="workflow-check"><input type="checkbox" checked={form.external_processing_approved} onChange={event => setForm({ ...form, external_processing_approved: event.target.checked })} />Our institution approves sending documents to the configured external parser.</label><p>This approval enables external processing for managed cases. It does not configure vendor regions or retention.</p>
    <label className="workflow-check"><input type="checkbox" checked={form.fictional_example_enabled} onChange={event => setForm({ ...form, fictional_example_enabled: event.target.checked })} />Enable the fictional training walkthrough.</label>
    <button className="primary-button" disabled={action.busy}>Save institution settings</button></form></Panel>
    <Panel title="Published program readiness">{programs.data?.map(program => <p key={program.id}>{program.name} · {program.active_version_id ? "Published criteria ready" : "Draft only"}</p>)}<button className="secondary-button" onClick={() => go("programs")}>Manage programs</button></Panel>{context.settings.fictional_example_enabled ? <button className="secondary-button" onClick={() => go("training")}>Open fictional walkthrough</button> : null}
  </>;
}

export function ExchangePage() {
  const load = useLoad<Exchange>("/exchange/history"); const action = useAction(load.refresh); const [selected, setSelected] = useState<ImportBatch | null>(null); const [file, setFile] = useState<File | null>(null);
  return <><State {...load} /><Banner {...action} /><Panel title="Application CSV exchange"><p>Preview rows before committing. Identity is matched by university system IDs; candidate names do not determine identity.</p><div className="workflow-toolbar"><button className="secondary-button" disabled={action.busy} onClick={() => void action.run(() => download("/exchange/template.csv", "applications-template.csv"), "CSV template downloaded.")}>Download CSV template</button><button className="secondary-button" disabled={action.busy} onClick={() => void action.run(() => download("/exchange/scores.csv", "signed-review-scores.csv"), "Signed scores exported.")}>Export current signed scores</button></div>
    <form className="workflow-form" onSubmit={event => { event.preventDefault(); if (!file) return; void action.run(async () => setSelected(await opsFile<ImportBatch>("/exchange/import/preview", file)), "Preview ready. Review conflicts and changes before committing."); }}><Field label="Application CSV"><input type="file" accept=".csv,text/csv" required onChange={event => setFile(event.target.files?.[0] ?? null)} /></Field><p>UTF-8 · up to 5 MB and 5,000 rows</p><button className="primary-button" disabled={action.busy || !file}>Preview import</button></form>
  </Panel>{selected ? <Panel title={`Import preview: ${selected.filename}`}><p>{selected.rows.length} rows · {selected.status}</p><Table headings={["CSV row", "Source application", "Candidate", "Program / cycle", "Action", "Details"]}>{selected.rows.map(row => <tr key={row.row_number}><td>{row.row_number}</td><td>{row.values.external_application_id}</td><td>{row.values.applicant_name}<small>{row.values.external_candidate_id}</small></td><td>{row.values.program_code} / {row.values.cycle}</td><td>{row.status}</td><td>{row.message}{row.changes ? <ul>{Object.entries(row.changes).map(([key, values]) => <li key={key}>{human(key)}: {values.from} → {values.to}</li>)}</ul> : null}</td></tr>)}</Table>{selected.status === "preview" ? <button className="primary-button" disabled={action.busy || !selected.rows.some(row => ["create", "update", "unchanged"].includes(row.status))} onClick={() => void action.run(async () => setSelected(await ops<ImportBatch>(`/exchange/import/${selected.id}/commit`, "POST")), "Valid rows committed. Conflicts remain listed.")}>Commit valid rows</button> : null}</Panel> : null}
    <Panel title="Import history">{load.data?.imports.map(batch => <p key={batch.id}><button className="ghost-button" onClick={() => setSelected(batch)}>{batch.filename} · {batch.rows.length} rows · {batch.status} · {date(batch.created_at)}</button></p>)}{!load.data?.imports.length ? <Empty>No CSV imports yet.</Empty> : null}</Panel>
    <Panel title="Export history"><Table headings={["Export batch", "Rows", "When", "Supersedes"]}>{load.data?.exports.map(batch => <tr key={batch.id}><td><code>{batch.id}</code></td><td>{batch.row_count}</td><td>{date(batch.created_at)}</td><td>{batch.supersedes_export_id || "—"}</td></tr>)}</Table></Panel>
  </>;
}

export function TrainingPage() {
  const load = useLoad<Training>("/training"); const [scores, setScores] = useState<Record<string, number>>({}); const [notes, setNotes] = useState<Record<string, string>>({}); const [receipt, setReceipt] = useState(false);
  return <><State {...load} />{load.data ? <><p className="notice notice-warning">Fictional training only. Nothing here is saved to live cases.</p><Panel title={`${load.data.candidate} · ${load.data.program}`}><div className="workflow-grid"><div><h3>Fictional originals</h3>{load.data.documents.map(document => <article className="workflow-card" id={document.id} key={document.id}><h4>{document.id} · page {document.page}</h4><pre>{document.text}</pre></article>)}</div><form onSubmit={event => { event.preventDefault(); setReceipt(true); }}><h3>Practice review</h3>{load.data.criteria.map(criterion => <fieldset className="workflow-card" key={criterion.key}><legend>{criterion.label}</legend><a href={`#${criterion.document_id}`} onClick={event => { event.preventDefault(); document.getElementById(criterion.document_id)?.scrollIntoView({ behavior: "smooth" }); }}>Source {criterion.document_id}, page {criterion.page}</a><Field label={`Sample score for ${criterion.label}`}><input type="number" required min={0} max={criterion.weight} value={scores[criterion.key] ?? ""} onChange={event => { setScores({ ...scores, [criterion.key]: Number(event.target.value) }); setReceipt(false); }} /></Field><Field label={`Sample rationale for ${criterion.label}`}><textarea required value={notes[criterion.key] ?? ""} onChange={event => setNotes({ ...notes, [criterion.key]: event.target.value })} /></Field><label className="workflow-check"><input type="checkbox" required />I compared this criterion with the fictional original.</label></fieldset>)}<button className="primary-button">Preview sample review</button><button className="secondary-button" type="button" onClick={() => { setScores({}); setNotes({}); setReceipt(false); }}>Reset sample scores</button></form></div></Panel>{receipt ? <Panel title="Sample review receipt"><p>{Object.values(scores).reduce((sum, value) => sum + value, 0)} / 100 · Criteria v{load.data.template_version} · Revision {load.data.case_revision}</p>{Object.entries(notes).map(([key, note]) => <p key={key}>{key}: {note}</p>)}<p>Preview only; no live review or admissions decision was saved.</p></Panel> : null}</> : null}</>;
}
