import { useEffect, useState } from "react";
import type { Case, Detail, Document, Evidence, ExtractedField, People, Program, Requirement, ReviewInput } from "./api";
import { ops, opsFile, sourceBlob } from "./api";
import { Banner, Empty, Field, Panel, Progress, State, Table, date, go, human, message, useAction, useLoad } from "./shared";

export default function CaseDetail({ id, tab, canManage, reviewer }: { id: string; tab: string; canManage: boolean; reviewer: boolean }) {
  const load = useLoad<Detail>(`/cases/${id}`); const people = useLoad<People>(canManage ? "/people" : null); const programs = useLoad<Program[]>(canManage ? "/programs" : null); const related = useLoad<Case[]>(load.data ? `/cases?q=${load.data.case.candidate_id}` : null);
  const action = useAction(load.refresh); const [documentId, setDocumentId] = useState<string | null>(null);
  useEffect(() => { if (!load.data?.documents.some(d => ["queued", "processing"].includes(d.status))) return; const timer = window.setInterval(load.refresh, 3000); return () => window.clearInterval(timer); }, [load.data?.documents, load.refresh]);
  const detail = load.data;
  return <><State {...load} /><Banner {...action} />{detail ? <>
    <div className="workflow-case-header"><div><a href="#/operations/applications">← All applications</a><h2>{detail.case.applicant_name}</h2><p>{detail.case.program_name} · {detail.case.intake_term} · {detail.template ? `Criteria v${detail.case.template_version}` : "Legacy criteria unassigned"} · Evidence revision {detail.case.case_revision}</p></div><div><Progress value={detail.case.completeness} /><p>{human(detail.case.status)}</p><button className="secondary-button" onClick={load.refresh}>Refresh case</button></div></div>
    <div className="workflow-identity"><span>Candidate UUID <code>{detail.case.candidate_id}</code></span>{detail.aliases.map(alias => <span key={alias.id}>{alias.source.toUpperCase()} ID <strong>{alias.value}</strong></span>)}<span>Application ID <code>{id}</code></span></div>
    <nav className="workflow-tabs" aria-label="Case sections">{["overview", "requirements", "documents", "evaluation", "activity"].map(section => <a className={tab === section ? "active" : ""} key={section} href={`#/operations/case/${id}/${section}`}>{human(section)}</a>)}</nav>
    {tab === "overview" ? <><Panel title="Application readiness"><p>{detail.case.missing_requirements} blocking requirements missing · {detail.documents.length} document versions</p><p>Each application keeps its criteria version and source history.</p><button className="primary-button" onClick={() => go(`case/${id}/${detail.case.completeness === 100 ? "evaluation" : "requirements"}`)}>Continue case</button></Panel>
      <Panel title="Other applications for this candidate">{related.data?.map(item => <p key={item.id}><a href={`#/operations/case/${item.id}/overview`}>{item.program_name} · {item.intake_term}</a></p>)}</Panel>
      {canManage ? <Panel title="Link a university system identifier"><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(`/cases/${id}/aliases`, "POST", { source: form.get("source"), value: form.get("value") })); }}><Field label="Identifier source"><select name="source"><option value="sis">SIS</option><option value="crm">CRM</option><option value="portal">Portal</option></select></Field><Field label="External identifier"><input name="value" required maxLength={120} /></Field><button className="secondary-button" disabled={action.busy}>Link identifier</button></form></Panel> : null}
    </> : null}
    {!detail.template && canManage ? <Panel title="Assign criteria to this legacy case"><p>Existing originals stay available. New requirements must be fulfilled explicitly; documents are not mapped automatically.</p><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(`/cases/${id}/pin-program`, "POST", { source: "sis", value: form.get("program") })); }}><Field label="Published program"><select name="program" required><option value="">Choose a published program</option>{programs.data?.filter(p => p.active_version_id).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><button className="primary-button" disabled={action.busy}>Pin program criteria</button></form></Panel> : null}
    {tab === "requirements" ? <><Panel title="Pinned evidence checklist"><p>Completeness uses required items; optional evidence does not block review.</p>{!detail.requirements.length ? <Empty>No criteria requirements have been assigned to this legacy case.</Empty> : null}</Panel>
      {detail.requirements.map(requirement => <RequirementCard key={`${requirement.id}:${requirement.revision}`} caseId={id} requirement={requirement} detail={detail} canManage={canManage} refresh={load.refresh} />)}
    </> : null}
    {tab === "documents" ? <Panel title="Document versions"><Table headings={["Document", "Requirement / slot", "Version", "Processing", "Received", "Source"]}>{detail.documents.map(document => <tr key={document.id}><td>{document.filename}{document.late ? <small className="workflow-warning">Late submission</small> : null}</td><td>{detail.requirements.find(r => r.id === document.requirement_id)?.label ?? "Legacy original"} · {document.slot ?? "—"}</td><td>v{document.version} · {document.current ? "Current" : "Superseded"}</td><td>{document.status}{document.error ? <small role="alert">{document.error}</small> : null}</td><td>{date(document.received_at)}<small>{human(document.channel)}</small></td><td><button className="secondary-button" onClick={() => setDocumentId(document.id)}>{document.status === "completed" ? "Review classification & fields" : "View original"}</button></td></tr>)}</Table>{!detail.documents.length ? <Empty>No documents received.</Empty> : null}</Panel> : null}
    {tab === "evaluation" ? <>
      {detail.evidence.issues.length ? <Panel title="Resolve before signing"><ul>{detail.evidence.issues.map(issue => <li key={issue}>{issue}</li>)}</ul>{detail.evidence.conflicts.map(conflict => <p key={conflict.key}><strong>{conflict.label}</strong>: {conflict.entries.map(e => `${e.filename}: ${e.effective_value}`).join("; ")}</p>)}<button className="secondary-button" onClick={() => go(`case/${id}/documents`)}>Inspect source evidence</button></Panel> : null}
      {canManage ? <Panel title="Assign reviewer"><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(`/cases/${id}/assign`, "POST", { reviewer_id: form.get("reviewer"), priority: form.get("priority"), due_at: form.get("due_at") || null })); }}><Field label="Reviewer"><select name="reviewer" required><option value="">Choose reviewer</option>{people.data?.people.filter(person => person.role === "reviewer" && person.status === "active").map(person => <option key={person.id} value={person.user_id}>{person.email} · {person.open_reviews}/{person.workload_limit} open</option>)}</select></Field><Field label="Priority"><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><Field label="Review due date"><input type="date" name="due_at" /></Field><button className="primary-button" disabled={action.busy || detail.case.completeness < 100}>Assign reviewer</button></form><p>{detail.assignments.map(a => `${a.reviewer_email} · ${a.priority} · due ${a.due_at || "not set"}`).join("; ") || "No reviewer assigned."}</p></Panel> : null}
      {reviewer && detail.template ? detail.own_review_signed ? <Panel title="Review signed"><p>Your review for this evidence revision is preserved. Evidence changes will reopen the review form.</p></Panel> : <ReviewForm key={`${id}:${detail.case.case_revision}`} detail={detail} refresh={load.refresh} onSource={setDocumentId} /> : null}
      <Panel title="Signed review history">{detail.reviews.map(review => <article className="workflow-card" key={review.id}><strong>{review.reviewer_email} · {Object.keys(review.scores).length ? `${review.total_score} / 100` : "Checklist review signed"}</strong><p>{date(review.submitted_at)} · Criteria v{review.template_version} · Evidence revision {review.case_revision} · {review.case_revision === detail.case.case_revision ? "Current" : "Requires rechecking"}</p><p>{review.comments}</p><Table headings={["Criterion", "Score", "Notes"]}>{Object.entries(review.scores).map(([key, score]) => <tr key={key}><td>{detail.template?.criteria.find(c => c.key === key)?.label ?? key}</td><td>{score}</td><td>{review.criterion_notes[key]}</td></tr>)}</Table></article>)}{!detail.reviews.length ? <Empty>No signed reviews yet. Official outcomes remain in the university system.</Empty> : null}</Panel>
    </> : null}
    {tab === "activity" ? <Panel title="Case activity"><Table headings={["When", "Actor", "Action"]}>{detail.activity.map(item => <tr key={item.id}><td>{date(item.timestamp)}</td><td>{item.actor}</td><td>{human(item.action)}</td></tr>)}</Table></Panel> : null}
    {documentId ? <EvidenceViewer key={documentId} caseId={id} document={detail.documents.find(d => d.id === documentId)!} editable={canManage || reviewer} onClose={() => setDocumentId(null)} refresh={load.refresh} /> : null}
  </> : null}</>;
}

function RequirementCard({ caseId, requirement, detail, canManage, refresh }: { caseId: string; requirement: Requirement; detail: Detail; canManage: boolean; refresh: () => void }) {
  const action = useAction(refresh); const [link, setLink] = useState(""); const [file, setFile] = useState<File | null>(null); const [slot, setSlot] = useState("");
  const current = detail.documents.filter(d => d.requirement_id === requirement.id && d.current);
  const base = `/cases/${caseId}/requirements/${requirement.id}`;
  return <Panel title={requirement.label}><p>{requirement.required ? "Required" : "Optional"} · {requirement.min_count}–{requirement.max_count} items · {human(requirement.status)} · Due {date(requirement.due_at)}</p><p>{requirement.instructions}</p><Banner {...action} />
    {requirement.waiver_reason ? <p><strong>Waived:</strong> {requirement.waiver_reason}</p> : null}
    {requirement.values?.map(value => <p key={value.slot}><strong>Verified value, slot {value.slot}:</strong> {value.value} · {value.verified_by} · {date(value.verified_at)}</p>)}
    {requirement.value_history?.length ? <details><summary>Verified value history</summary>{requirement.value_history.map((entry, index) => <pre key={index}>{JSON.stringify(entry, null, 2)}</pre>)}</details> : null}
    {current.map(document => <p key={document.id}>Slot {document.slot} · {document.filename} · v{document.version} · {document.status}{document.late ? " · Late" : ""}</p>)}
    {canManage && detail.case.status !== "withdrawn" ? <>
      {requirement.capture_type === "document" && requirement.upload_channels.includes("staff") ? <form className="workflow-form" onSubmit={event => { event.preventDefault(); if (!file) return; void action.run(() => opsFile(base + "/upload", file, slot ? { slot } : {}), "Document received. Processing will update this case."); }}><Field label={`File for ${requirement.label}`}><input type="file" required accept={requirement.allowed_extensions.join(",")} onChange={event => setFile(event.target.files?.[0] ?? null)} /></Field><Field label="Destination slot"><select value={slot} onChange={event => setSlot(event.target.value)}><option value="">Next empty slot</option>{current.map(document => <option key={document.id} value={document.slot ?? ""}>Replace slot {document.slot}: {document.filename}</option>)}</select></Field><button className="primary-button" disabled={action.busy || !file}>Upload evidence</button></form> : requirement.capture_type !== "document" ? <form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(base + "/value", "PUT", { value: String(form.get("value")), revision: requirement.revision, ...(slot ? { slot: Number(slot) } : {}) })); }}><Field label="Verified requirement value"><input name="value" required type={requirement.capture_type === "number" ? "number" : "text"} step="any" defaultValue={requirement.max_count === 1 ? requirement.value ?? "" : ""} /></Field>{requirement.max_count > 1 ? <Field label="Value destination slot"><select value={slot} onChange={event => setSlot(event.target.value)}><option value="">Next empty slot</option>{requirement.values?.map(value => <option key={value.slot} value={value.slot}>Replace slot {value.slot}: {value.value}</option>)}</select></Field> : null}<button className="primary-button" disabled={action.busy}>Save verified evidence</button></form> : null}
      {requirement.capture_type === "document" && requirement.upload_channels.includes("secure_link") ? <form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(async () => { const created = await ops<{ path: string }>(base + "/links", "POST", { expiry_days: form.get("days") ? Number(form.get("days")) : null, max_uploads: Number(form.get("uploads")) }); setLink(window.location.href.split("#")[0] + created.path); }, "Secure upload link created. Copy it now."); }}><Field label="Link expiry days (optional)"><input type="number" name="days" min={1} max={90} /></Field><Field label="Maximum uploads"><input type="number" name="uploads" min={1} max={requirement.max_count} defaultValue={1} /></Field><button className="secondary-button" disabled={action.busy}>Create secure link</button></form> : null}
      {link ? <div className="workflow-toolbar"><Field label="Generated secure upload link"><input readOnly value={link} /></Field><button className="secondary-button" onClick={() => void action.run(() => navigator.clipboard.writeText(link), "Link copied.")}>Copy link</button></div> : null}
      {detail.links.filter(item => item.requirement_id === requirement.id).map(item => <p key={item.id}>Link expires {date(item.expires_at)} · {item.uploads}/{item.max_uploads} uploads · {item.revoked ? "Revoked" : "Active"} {!item.revoked ? <button className="ghost-button" disabled={action.busy} onClick={() => void action.run(() => ops(`/links/${item.id}/revoke`, "POST"))}>Revoke link</button> : null}</p>)}
      {requirement.required ? <details><summary>Waive requirement</summary><form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(base + "/waive", "POST", { reason: form.get("reason"), revision: requirement.revision })); }}><Field label="Waiver reason"><textarea name="reason" required maxLength={2000} /></Field><button className="secondary-button" disabled={action.busy}>Record waiver</button></form></details> : null}
    </> : null}</Panel>;
}

function ReviewForm({ detail, refresh, onSource }: { detail: Detail; refresh: () => void; onSource: (id: string) => void }) {
  const freshDraft = detail.draft?.case_revision === detail.case.case_revision ? detail.draft : null;
  const [form, setForm] = useState<ReviewInput>(() => ({ scores: freshDraft?.scores ?? {}, criterion_notes: freshDraft?.criterion_notes ?? {}, comments: freshDraft?.comments ?? "", revision: detail.case.case_revision, source_verified: false, conflict_declared: false }));
  const [dirty, setDirty] = useState(false); const [saved, setSaved] = useState(freshDraft?.saved_at ?? ""); const [saveError, setSaveError] = useState(""); const action = useAction(refresh);
  useEffect(() => { if (!dirty) return; let active = true; const timer = window.setTimeout(() => {
    ops<{ saved_at: string }>(`/cases/${detail.case.id}/review/draft`, "PUT", form).then(result => { if (active) { setSaved(result.saved_at); setDirty(false); setSaveError(""); } }).catch(error => { if (active) setSaveError(message(error)); });
  }, 1000); return () => { active = false; window.clearTimeout(timer); }; }, [form, dirty, detail.case.id]);
  const update = (values: Partial<ReviewInput>) => { setForm(previous => ({ ...previous, ...values })); setDirty(true); };
  return <Panel title="Human verified review"><Banner {...action} error={action.error || saveError} /><p>Numeric scores are entered by you. AI extraction is decision support. Official outcomes remain in the university system.</p><p role="status">{saveError ? "Draft not saved. Retry before signing." : dirty ? "Saving draft…" : saved ? `Draft saved ${date(saved)}` : "Draft not saved yet."}</p>{saveError ? <button className="secondary-button" onClick={() => setForm(previous => ({ ...previous }))}>Retry saving draft</button> : null}
    <form onSubmit={event => { event.preventDefault(); void action.run(() => ops(`/cases/${detail.case.id}/review/sign`, "POST", form), "Review signed. Its evidence revision and criteria are preserved."); }}>
      {detail.template?.criteria.map(criterion => <fieldset className="workflow-card" key={criterion.key}><legend>{criterion.label} · {criterion.weight} points</legend><p>{criterion.instructions}</p>
        <div className="workflow-toolbar">{detail.documents.filter(document => document.current && detail.requirements.some(r => r.id === document.requirement_id && criterion.evidence_keys.includes(r.key))).map(document => <button className="secondary-button" type="button" key={document.id} onClick={() => onSource(document.id)}>Inspect {document.filename}</button>)}</div>
        <Field label={`Score for ${criterion.label}`}><input type="number" required min={0} max={criterion.weight} step="any" value={form.scores[criterion.key] ?? ""} onChange={event => { const scores = { ...form.scores }; if (event.target.value === "") delete scores[criterion.key]; else scores[criterion.key] = Number(event.target.value); update({ scores }); }} /></Field>
        <Field label={`Notes for ${criterion.label}`}><textarea maxLength={2000} value={form.criterion_notes[criterion.key] ?? ""} onChange={event => update({ criterion_notes: { ...form.criterion_notes, [criterion.key]: event.target.value } })} /></Field>
      </fieldset>)}
      <Field label="Overall reviewer comments"><textarea maxLength={5000} value={form.comments} onChange={event => update({ comments: event.target.value })} /></Field>
      <label className="workflow-check"><input type="checkbox" required checked={form.source_verified} onChange={event => update({ source_verified: event.target.checked })} />I checked the original source evidence against the pinned criteria.</label>
      <label className="workflow-check"><input type="checkbox" checked={form.conflict_declared} onChange={event => update({ conflict_declared: event.target.checked })} />I have a conflict of interest; contact the admissions manager.</label>
      <button className="primary-button" disabled={action.busy || dirty || detail.evidence.issues.length > 0 || detail.case.completeness < 100 || form.conflict_declared}>Sign review for revision {detail.case.case_revision}</button>
    </form>
  </Panel>;
}

function EvidenceViewer({ caseId, document, editable, onClose, refresh }: { caseId: string; document: Document; editable: boolean; onClose: () => void; refresh: () => void }) {
  const base = `/cases/${caseId}/documents/${document.id}`; const load = useLoad<Evidence>(document.status === "completed" ? base + "/evidence" : null);
  const [sourceUrl, setSourceUrl] = useState(""); const [sourceError, setSourceError] = useState(""); const [page, setPage] = useState(0);
  const action = useAction(() => { load.refresh(); refresh(); });
  useEffect(() => { let active = true; let url = ""; sourceBlob(base + "/source").then(blob => { url = URL.createObjectURL(blob); if (active) setSourceUrl(url); else URL.revokeObjectURL(url); }).catch(error => { if (active) setSourceError(message(error)); }); return () => { active = false; if (url) URL.revokeObjectURL(url); }; }, [base]);
  const analysis = load.data; const canEdit = editable && document.current;
  return <section className="workflow-evidence" aria-label={`Evidence for ${document.filename}`}><div className="workflow-toolbar"><h2>{document.filename} · {document.current ? "Current" : "Superseded (read only)"}</h2><button className="secondary-button" onClick={onClose}>Close evidence</button></div><Banner error={sourceError} /><div className="workflow-grid workflow-source-grid"><div><State {...load} /><Banner {...action} />
    {analysis ? <><h3>Document classification</h3><p>Suggested: {human(analysis.proposed_type)} · {analysis.classification_state}{analysis.staff_type ? ` · Staff confirmed: ${human(analysis.staff_type)}` : ""}</p>
      {canEdit ? <form className="workflow-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(() => ops(base + "/evidence", "PUT", { revision: analysis.revision, status: "verified", value: form.get("type"), reason: form.get("reason") })); }}><Field label="Confirmed document type"><select name="type" defaultValue={analysis.staff_type ?? analysis.proposed_type}>{Object.entries(analysis.document_types ?? {}).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Classification reason"><textarea name="reason" required maxLength={2000} /></Field><button className="secondary-button" disabled={action.busy}>Confirm type</button></form> : null}
      <h3>Extracted fields</h3>{analysis.fields.map(field => <FieldReview key={`${field.id}:${analysis.revision}`} field={field} analysis={analysis} canEdit={canEdit} busy={action.busy} onSource={setPage} onSave={values => action.run(() => ops(base + "/evidence", "PUT", { ...values, field_id: field.id, revision: analysis.revision }))} />)}{!analysis.fields.length ? <Empty>No explicitly labeled fields were extracted. Inspect the original.</Empty> : null}
      <h3>Staff correction history</h3>{analysis.history.map((item, index) => <details key={index}><summary>{item.actor} · {date(item.at)}</summary><pre>{JSON.stringify({ before: item.before, after: item.after }, null, 2)}</pre></details>)}
    </> : null}
  </div><aside className="workflow-source"><h3>Original evidence</h3>{sourceUrl ? <><a href={sourceUrl} download={document.filename}>Download original</a>{/\.(pdf|png|jpe?g|txt)$/i.test(document.filename) ? <iframe title={`Original ${document.filename}`} src={sourceUrl + (/\.pdf$/i.test(document.filename) && analysis?.pages[page]?.number ? `#page=${analysis.pages[page].number}` : "")} /> : <p>Download this Office document to inspect it.</p>}</> : <p>Loading original…</p>}
    {analysis ? <><Field label="Parsed source reference"><select value={page} onChange={event => setPage(Number(event.target.value))}>{analysis.pages.map((item, index) => <option key={index} value={index}>{item.number ? `Source page ${item.number}` : `Parsed text ${index + 1} · page unavailable`}</option>)}</select></Field><pre>{analysis.pages[page]?.text}</pre></> : null}
  </aside></div></section>;
}

function FieldReview({ field, analysis, canEdit, busy, onSource, onSave }: { field: ExtractedField; analysis: Evidence; canEdit: boolean; busy: boolean; onSource: (index: number) => void; onSave: (values: object) => Promise<boolean> }) {
  const [status, setStatus] = useState("verified");
  return <article className="workflow-card"><h4>{field.label}</h4><p>Original suggestion: <strong>{field.suggested_value}</strong> · {field.staff_status}</p>{field.staff_status === "corrected" ? <p>Staff corrected value: {field.staff_value}</p> : null}{field.uncertainty ? <p className="workflow-warning">{field.uncertainty}</p> : null}{field.citations.map((citation, index) => <div key={index}><blockquote>{citation.quote}</blockquote><button className="ghost-button" onClick={() => onSource(citation.page_index)}>{citation.page ? `Source page ${citation.page}` : "Page unavailable"} · line {citation.line}</button></div>)}{field.staff_citation ? <blockquote>Corrected source: {field.staff_citation.quote}</blockquote> : null}{field.reason ? <p>Staff reason: {field.reason}</p> : null}
    {canEdit ? <details><summary>Verify, correct or reject</summary><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void onSave({ status, value: String(form.get("value") ?? ""), reason: String(form.get("reason") ?? ""), source_index: status === "corrected" ? Number(form.get("source_index")) : null, source_quote: String(form.get("source_quote") ?? "") }); }}>
      <Field label="Staff action"><select value={status} onChange={event => setStatus(event.target.value)}><option value="verified">Verify original extraction</option><option value="corrected">Correct value</option><option value="rejected">Reject extraction</option></select></Field>
      {status === "corrected" ? <><Field label="Corrected value"><input name="value" required maxLength={300} /></Field><Field label="Supporting source reference"><select name="source_index">{analysis.pages.map((page, index) => <option key={index} value={index}>{page.number ? `Page ${page.number}` : `Parsed text ${index + 1} (page unavailable)`}</option>)}</select></Field><Field label="Exact supporting quote"><textarea name="source_quote" required maxLength={1000} /></Field></> : null}
      <Field label="Staff reason"><textarea name="reason" required={status !== "verified"} maxLength={2000} /></Field><button className="secondary-button" disabled={busy}>Save staff decision</button>
    </form></details> : null}
  </article>;
}
